# Generated by Django 2.2.1 on 2019-05-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crush',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('qualidade', models.CharField(max_length=100)),
                ('defeito', models.CharField(default='não está comigo', max_length=100)),
                ('signo', models.CharField(max_length=100)),
                ('reciproco', models.BooleanField(default=False)),
                ('solteiro', models.BooleanField(default=False)),
            ],
        ),
    ]
