# Generated by Django 2.2.1 on 2019-05-06 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poxa_crush', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crush',
            name='foto',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='crush',
            name='signo',
            field=models.CharField(choices=[('ar', 'áries'), ('tr', 'touro'), ('ge', 'gêmeos'), ('cr', 'câncer'), ('le', 'leão'), ('vr', 'virgem'), ('lb', 'libra'), ('es', 'escorpião'), ('sg', 'sagitário'), ('cp', 'capricornio'), ('aq', 'aquário'), ('px', 'peixes')], max_length=2),
        ),
    ]
